### ISSUE TITLE
Crash on filter screen in split screen

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#331]
How reproduce:
- Start app
- Open another app and enable split screen
- Press filter button to open pop-up menu
- Rotate screen
- Press Update filter button -> crash

```
FATAL EXCEPTION: main
Process: net.vonforst.evmap, PID: 13712
java.lang.IllegalStateException: Fragment MapFragment{f4d538a} (93880ff9-4695-4747-b165-21f5ac38af0f) did not return a View from onCreateView() or this was called before onCreateView().
at androidx.fragment.app.Fragment.requireView(Fragment.java:2062)
at net.vonforst.evmap.fragment.MapFragment.onCreateMenu$lambda$78$lambda$77(MapFragment.kt:1362)
at net.vonforst.evmap.fragment.MapFragment.$r8$lambda$AArRgwSm0UbWjnQdhGFyQ_LN-4U(Unknown Source:0)
at net.vonforst.evmap.fragment.MapFragment$$ExternalSyntheticLambda20.onMenuItemClick(Unknown Source:4)
at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1271)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3284)
at android.widget.AbsListView$3.run(AbsListView.java:4250)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
2024-04-25 20:26:21.897 13712-13712 ACRA                    net.vonforst.evmap                   E  ACRA caught a IllegalStateException for net.vonforst.evmap
java.lang.IllegalStateException: Fragment MapFragment{f4d538a} (93880ff9-4695-4747-b165-21f5ac38af0f) did not return a View from onCreateView() or this was called before onCreateView().
at androidx.fragment.app.Fragment.requireView(Fragment.java:2062)
at net.vonforst.evmap.fragment.MapFragment.onCreateMenu$lambda$78$lambda$77(MapFragment.kt:1362)
at net.vonforst.evmap.fragment.MapFragment.$r8$lambda$AArRgwSm0UbWjnQdhGFyQ_LN-4U(Unknown Source:0)
at net.vonforst.evmap.fragment.MapFragment$$ExternalSyntheticLambda20.onMenuItemClick(Unknown Source:4)
at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
at android.widget.AdapterView.performItemClick(AdapterView.java:330)
at android.widget.AbsListView.performItemClick(AbsListView.java:1271)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3284)
at android.widget.AbsListView$3.run(AbsListView.java:4250)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by johan12345** [comment]
Interesting, it seems like the popup menu is usually dismissed when the device is rotated, only in split-screen mode it stays open and then keeps references to the old, destroyed fragment.

As a simple solution, for now, I just made sure that the popup menu is dismissed in `onDestroy` in 75e8569 - just like it has already been the case without splitscreen.
